name: ci
on:
  push:
  pull_request:
jobs:
  workspace:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: Levalicious/mk@477dc780cdfe992debfb0c07a4d9893deb5aa8db
      - uses: Levalicious/mkroot@36d0977adb014e0e2775222d23ce522ddde8b570
      - run: mk
      - run: (cd stdlib && mk install)
      - run: mk test
