name: ci
on:
  push:
  pull_request:
jobs:
  workspace:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: Levalicious/mk@2e9df12fdc3a4d9a2793cb2d6d641817bd83cbbc
      - uses: Levalicious/mkroot@38fc598680d6b47b13e4ac2b1f2d303023ba30d5
      - run: mk
      - run: (cd stdlib && mk install)
      - run: mk test
