name: ci
on:
  push:
  pull_request:
jobs:
  workspace:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: Levalicious/mk@8b33eaa94d5ae53a70b0f3b2cfd9fb1432f8cc9e
      - uses: Levalicious/mkroot@f7addbfe0a8b91de9ef1e0247453f058e3d3fc3a
      - run: mk
      - run: (cd stdlib && mk install)
      - run: mk test
